### ISSUE TITLE
Image to image 

### ISSUE THREAD

**Issue by alelordelo** [The-Igor/replicate-kit-swift#1]
Thanks for sharing! Also working on SD serveless SwiftUI  right now…

Did you get image to image to work?

**Comment by swiftuiux** [comment]
I've been thinking about image to image if I do I'll put it out as open source 🙂

**Comment by alelordelo** [comment]
Thanks! Looking forward to check it! : )


This package has image to image, haven't tested yet tho...
https://github.com/mattt/replicate-swift

        /// Inital image to generate variations of. Will be resized to the specified width and height
    `    public var initImage: URL?`
        
        


https://replicate.com/cloneofsimo/lora

**Comment by swiftuiux** [comment]
Thank you 🙂
